Update v_ksm_data_mart.sql
phively/nu-plsql pull request #94
Opened 2021-09-17 22:48 UTC by ssocite

New modifications to the giving piece of the data mart views.

2021-09-29 15:14 UTC, phively requested changes
-- Looks like the ellipses … in the comments on lines 587 and 600 are causing issues – you can replace with a comma
-- Update anonymous filtering: also drop if spouse is fully anonymous! No need to have logic for individual gifts, just the "a" subquery - easiest would be to left join on spouse_id_number
-- LAST_GIFT_FY needs to be fixed; should use the hh subquery, not call directly from v_ksm_giving_summary, to adhere to the anonymous gift logic

2021-09-29 15:14 UTC, phively commented on views/v_ksm_data_mart.sql
> +from RPT_PBH634.v_Ksm_Giving_Summary give), --- stewardship amount
This does not follow the anonymous special handling rules used in the hh subquery. Remove v_ksm_giving_summary and use hh instead, e.g.
rpt_pbh634.get_fiscal_year(max(hh.date_of_record)) as last_gift_fy
on line 605 (not tested)

2021-09-29 15:14 UTC, phively commented on views/v_ksm_data_mart.sql
> +where a.ANONYMOUS_DONOR is null
Let's also redact anyone whose spouse is null. Easiest way would just be to join on spouse_id_number e.g.
Left Join a a_spouse On a_spouse.spouse_id_number = degrees.id_number
and also add another condition
where a_spouse.anonymous_donor is null

2021-09-30 21:35 UTC, ssocite commented
Modifications to the data mart file and the mobile view file.

2021-09-30 21:37 UTC, ssocite commented on views/v_ksm_data_mart.sql
> +2) Drop individual gifts with anonymous type 1, 2, 3 for the purpose of calculating the suggested fields�or alternatively drop all such records
comma added

2021-09-30 21:37 UTC, ssocite commented on views/v_ksm_data_mart.sql
> +--- Drop individual gifts with anonymous type 1, 2, 3 for the purpose of calculating the suggested fields�or alternatively drop all such records
comma added

2021-10-01 15:26 UTC, merged